# a_tensor_initialization

In [10]:
import torch

# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu') 
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

print("#" * 50, 1)

# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)

a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

#추가코드------------------------------
a12 = torch.tensor([
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
])
print(a12.shape, a12.ndim)
#----------------------------------------


a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])



torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3
torch.Size([4, 1, 2, 3]) 4


ValueError: expected sequence of length 3 at dim 3 (got 2)

tensor의 사이즈와 깊이: tensor의 깊이(차원)은 축의 개수로 설명할 수 있으며, 사이즈의 경우 각 축의 원소 개수를 의미하고 텐서의 구조를 나타낸다.

tensor의 내부의 리스트는 모두 동일한 크기를 가지고 있어야 한다. 하지만 a11은 첫번째 항목과 두번째 항목의 크기가 3과 2로 다르기 때문에 오류가 발생한다.

# b_tensor_initialization_copy

In [4]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

#코드 추가
print("#" * 100)
print(l1, l2,l3,l4,l5,l6)
l6[0] = 200
l6[1] = 300
l6[2] = 400

print(l6)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)
####################################################################################################
[100, 2, 3] [100, 2, 3] [100, 2, 3] [100   2   3] [100   2   3] [100   2   3]
[200 300 400]
tensor([200, 300, 400], dtype=torch.int32)


list와 np.array의 텐서화

list와 np.array를 텐서로 변경할 때 두 자료형과 텐설 변환시키는 함수별 차이점을 확인하기 위한 코드로 보인다.
텐서를 만드는 함수로는 Tensor(), tensor(), as_tensor가 존재한다.

- Tensor(): pytorch의 기본 텐서 클래스로 크기를 입력해 원하는 구조의 텐서를 만들수 도 있으나 이 경우 초기값으로 임의의 값이 설정된다. 위에처럼 이미 존재하는 데이터를 만들 수 있다.
- tensor(): 주어진 데이터를 기반으로 텐서를 생성하는 함수이다. Tensor와 다르게 자동으로 데이터의 타입을 감지해 알맞은 데이터 타입의 텐서를 생성한다.
- as_tensor(): 주어진 데이터를 기반으로 텐서를 생성하는 함수이다. 데이터의 복사를 최소화하기 위해 기존 데이터의 메모리를 공유한다. 때문에 원본 데이터를 변경하면 텐서의 값도 변경된다. 하지만 list의 경우에는 리스트를 변경하면 해당 리스트가 참조하는 주소가 변경되는 것이기 때문에 list 자료형을 as_tensor로 텐서를 만든 경우 list를 변경해도 텐서에 변화는 없다.

# c_tensor_initialization_constant_values

In [5]:
import torch

t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3)
print(t4)


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([-1.2177e+32,  1.1154e-42,  3.0000e+00,  0.0000e+00])
tensor([1., 2., 3., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


ones, zeros, empty 등을 이용한 텐서의 생성과 like, eye를 이용한 텐서의 생성
- ones: 주어진 크기(구조)의 텐서를 생성하며, 모든 요소를 1로 초기화한다.
- zeros: 주어진 크기(구조)의 텐서를 생성하며, 모든 요소를 0으로 초기화한다.
- empty: 주어진 크기(구조)의 텐서를 생성하며, 모든 요소를 임의의 값으로 초기화한다.

- like: 주어진 텐서와 동일한 크기(구조)의 텐서를 생성한다. 앞쪽의 ones, zeros, empty중 무엇이 붙는지에 따라 원소의 초기화 값이 정해진다.

- eye: 주어진 크기의 단위 행렬인 텐서를 생성한다. n x m 크기의 행렬로 생성할 수 있다. 이 경우 주대각선의 요소는 모두 1이고 나머지 요소는 0인 행렬을 생성한다. 항상 차원이 2인 텐서이다.

# d_tensor_initialization_random_values

In [1]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)


tensor([[11, 13]])
tensor([[0.3695, 0.5365, 0.3038]])
tensor([[ 1.3246, -0.1589,  1.8702]])
tensor([[ 9.9485, 11.4228],
        [ 8.7230,  8.4463],
        [ 9.4099,  8.6061]])
tensor([0.0000, 2.5000, 5.0000])
torch.Size([3])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


랜덤값으로 초기화된 텐서의 생성
- randint(low, high, size): 주어진 low, high 범위에서 임의의 정수를 생성한다. 생성하는 텐서의 구조는 size를 따른다
- rand(size): 0과 1 사이의 값을 균등 분포로 선택해 임의의 실수를 생성한다. 생성하는 텐서의 구조는 size를 따른다.
- randn(size): 평균이 0 표준편차가 1인 정규 본포에 따라 임의의 실수를 생성한다. 생성하는 텐서의 구조는 size를 따른다.
- normal(mean, std, size): 입력받은 평균과 표준편차를 가지는 정규 분포에 따라 임의의 실수를 생성한다. 생성하는 텐서의 구조는 size를 따른다.
- linspace(start, end, steps): 입력받은 start와 end 사이의 값을 steps개 만큼 균등하게 나누서 값을 생성한다. 1차원의 텐서를 가진다.
- arange(a): 0부터 a까지의 정수를 생성한다. 1차언의 텐서를 가진다.
- manual_seed(): 난수 생성의 시드를 생성해 난수 생성을 재현 가능하도록 한다.
- rand(a,b): 0과 1사이의 값을 균등 분포로 선택해 임의의 실수로 생성한다. 생성하는 텐서의 구조는 a행 b열이다. 
- size = (a,b)


# e_tensor_type_conversion.py

In [3]:
import torch

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)
print(double_d.dtype) #추가 코드
print(short_e.dtype)  # 추가 코드

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()
print(double_d.dtype) # 추가 코드
print(short_e.dtype)  # 추가 코드

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)
print(double_d.dtype) # 추가 코드
print(short_e.dtype)  # 추가 코드

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[11.6692, 18.3283,  0.2118],
        [18.4972,  9.8370,  3.8937]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16
torch.float64


텐서의 타입 변경
- tensor.to(자료형): 해당 텐서를 입력한 자료형으로 변경
- tensor.to(device): 텐서를 cpu에서 gpu로 또는 gpu에서 cpu로 이동
- tensor.double(): 텐서의 자료형을 64비트 부동 소수점(torch.float64)으로 설정
- tensor.short(): 텐서의 자료형을 16비트 정수(torch.int16)로 설정
- tensor.type(자료형): 텐서를 입력받은 자료형으로 변경

# f_tensor_operations.py

In [7]:
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


텐서의 사칙연산 연산자와 함수
- 연산자: 가독성이 좋다.
- 함수: 추가 기능과 유연성 제공 (브로드캐스팅(두 텐서의 크기가 다른 경우 브로드캐스팅을 통해 크기를 맞춰준다.), in-place('add(t1,t2,out=t3)' 이렇게 기존 텐서에 저장 가능)

# g_tensor_operations_mm.py

In [17]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t2) #추가 코드
print(t3) #추가 코드
print(t4) #추가 코드
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t5) #추가 코드
print(t6) #추가 코드
print(t7.size())


#추가 코드 -------------------------------
print("추가 코드", end=" ")
print("#" * 30)
#matmul
#tensor1: 1차원, tensor2: 1차원인 경우
t8 = torch.randn(2)
t9 = torch.randn(2)
print(t8)
print(t9)
print(torch.matmul(t9,t8))

#tensor1: 1차원, tensor2: 2차원인 경우
t10 = torch.randn(2)
t11 = torch.randn(2,1)
print(t10)
print(t11)
print(torch.matmul(t10,t11))

#tensor1: 2차원, tensor2: 1차원인 경우
t10 = torch.randn(2,1)
t11 = torch.randn(1)
print(t10)
print(t11)
print(torch.matmul(t10,t11))

t10 = torch.randn(2)
t11 = torch.randn(2,1)
print(t10)
print(t11)
print(torch.matmul(t10,t11))

tensor(7) torch.Size([])
tensor([[ 0.4742,  0.9797,  0.7206],
        [ 0.3366,  0.6580, -0.5221]])
tensor([[-0.9168, -1.7845],
        [-0.6568,  1.1906],
        [-2.3959, -0.7807]])
tensor([[-2.8047, -0.2424],
        [ 0.5101,  0.5902]])
tensor([[-2.8047, -0.2424],
        [ 0.5101,  0.5902]]) torch.Size([2, 2])
tensor([[[ 0.4649,  1.0024, -0.4300,  0.0224],
         [-0.4577, -0.4615,  0.5496, -0.0871],
         [-0.1730,  1.6708, -0.0341,  1.0033]],

        [[ 1.1079, -1.0454,  1.6364, -0.0242],
         [-0.0278,  0.3844,  0.4644, -0.1355],
         [ 0.2364,  0.7613, -1.6597, -1.3178]],

        [[-0.7786, -0.2364, -0.8153,  0.3090],
         [-0.8037,  2.5264, -0.2621,  0.7512],
         [-0.0166,  1.6601,  1.7656, -0.9698]],

        [[ 0.2893,  0.4487,  0.8493,  1.8208],
         [-0.0544, -0.4368, -0.5627, -1.2856],
         [ 0.2076,  0.2787, -0.8574,  0.7197]],

        [[-0.1117,  0.9229,  0.2972,  2.2930],
         [-1.3505, -1.5121,  1.0961, -0.4439],
         [ 0.726

텐서의 행렬곱
- dot(tensor1, tensor2): 두 1차원 텐서의 내적(같은 인덱스의 값들을 곱한 후 sum) 스칼라값을 반환한다.
- mm(tensor1, tensor2): 두 2차원 텐서의 행렬 곱. nxm * mxp = nxp
- bmm(tensor1, tensor2): 두 3차원 텐서의 행렬 곱. bxnxm * bxmxp = bxnxp
- matmul(tensor1, tensor2): 입력받은 텐서의 형태에 따라 모드가 달라진다.
- - 두 tensor 모두 1차원 -> 내적(스칼라)이 반환
- - 두 tensor 모두 2차원 -> 행렬 곱이 반환. nxm * mxp = nxp
- - tensor1이 1차원, tensor2가 2차원 -> tensor1에 차원을 추가해 동일한 차원으로 만들고 행렬 곱을 실행한 후, 추가된 차원을 삭제. n * nxm = m
- - tensor1이 2차원, tensor2가 1차원 -> 행렬-벡터 곱. nxm * m = n

# h_tensor_operations_mmatmul.py

In [19]:
import torch

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])
#추가코드----------------------------------
print(t1)
print(t2)
print(torch.matmul(t1, t2))
print("#" * 30)
#-----------------------------------
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])
#추가코드----------------------------------
print(t3)
print(t4)
print(torch.matmul(t3, t4))
print("#" * 30)
#-----------------------------------
# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])
#추가코드----------------------------------
print(t5)
print(t6)
print(torch.matmul(t5, t6))
print("#" * 30)
#-----------------------------------
# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])
#추가코드----------------------------------
print(t7)
print(t8)
print(torch.matmul(t7, t8))
print("#" * 30)
#-----------------------------------
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])
#추가코드----------------------------------
print(t9)
print(t10)
print(torch.matmul(t9, t10))
print("#" * 30)
#-----------------------------------

torch.Size([])
tensor([-0.2807, -2.7677, -0.5109])
tensor([ 0.6968,  0.0761, -0.3318])
tensor(-0.2367)
##############################
torch.Size([3])
tensor([[-0.5861, -1.5804,  1.3590,  0.2994],
        [-0.5474,  1.4955,  1.0436,  0.1093],
        [-0.8899,  0.9766,  0.4052,  0.4546]])
tensor([-1.2611,  0.6301,  0.1542,  1.2123])
tensor([0.3159, 1.9262, 2.3513])
##############################
torch.Size([10, 3])
tensor([[[-0.8414,  1.3672,  0.7935,  0.5210],
         [ 1.8761, -0.3060,  0.3790, -0.2551],
         [-0.3607,  0.3743, -1.1030, -1.3587]],

        [[-1.3723, -0.6601,  0.1113, -0.3373],
         [ 1.2688,  1.2231,  0.0982,  0.3759],
         [ 0.1432,  0.1852, -0.3809, -0.2826]],

        [[-0.4288, -0.0769, -0.0326,  0.9893],
         [ 0.3531,  0.9210, -0.8385,  0.2855],
         [-0.2869, -0.5035,  1.7385,  1.1226]],

        [[-0.9890, -0.1535, -0.6454,  0.1235],
         [ 1.9671,  2.2096,  3.1521, -1.4426],
         [ 0.4087,  0.4806, -0.8396, -1.7623]],

        [[

matmul: 입력받은 텐서의 종류에 따라 모드가 달라진다.
- 두 텐서 모두 1차원인 경우 -> 벡터의 내적을 통해 스칼라값 반환
- tensor1: 2차원, tensor2: 1차원 -> 행렬과 벡터의 곱셈 수행. 1차원 배열을 반환. nxm * m = n
- tensor1: 3차원, tensor2: 1차원 -> 3차원 텐서의 마지막 2개 차원과 1차원 벡터의 곱셈 수행. 2차원 배열을 반환. nxmxp * p = nxm
- tensor1: 3차원, tensor2: 3차원 -> 두 3차원 텐서의 마지막 2개 차원을 행렬 곱셈을 수행. nxmxp * nxpxk = nxmxk
- tensor1: 3차원, tensor2: 2차원 -> 3차원 텐서의 마지막 2개 차원과 2차원 행렬의 곱셈을 수행. nxmxp * pxk = nxmxk

# i_tensor_broadcasting.py

In [20]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)


def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

브로드 캐스팅
- 스칼라와 벡터의 곱: 벡터의 모든 요소에 스칼라를 곱한다.
- 행려과 벡터의 차: 행렬의 각 행에서 벡터를 뺀다.
- 행렬에 스칼라값 사칙연산: 행렬의 모든 요소에 스칼라값을 연산자에 맞춰서 계산한다.
- pow 함수를 이용한 거듭제곱: (tensor1, n): tensor1의 각 요소를 n 만큼 거듭제곱한다. (tensor1, tensor2): tensor1의 요소를 tensor2의 동일 인덱스의 값만큼 거듭 제곱한다.

# j_tensor_indexing_slicing.py

In [21]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


index slicing
- x[n]      : 텐서 x의 n번 행 전체
- x[:, n]   : 텐서 x의 n번 열 전체
- x[n, m]   : 텐서 x의 n행 m열의 값
- x[:, -n]  : 텐서 x의 뒤에서 부터 n번째 열 전체(python은 음수 인덱스 사용 가능(-1부터 마지막 인덱스 -2는 마지막 인덱스의 이전 인덱스))
- x[n:]     : 텐서 x의 n번 행 부터 마지막 행까지
- x[n:, m:] : 텐서 x의 n번 행 부터 마지막 행까지 내용중 m번째 열부터 마지막 열까지 값
- y[n:m, k] = 1: 텐서 y의 n번 행부터 m-1행의 k열의 값을 1로 변경
- y[n:m, n:m]: 텐서 y의 n번 행부터 m-1행의 내용중 n번 열부터 m-1열의 값
- z[:n]     : 텐서 z의 0번 행부터 n-1행의 값
- z[n:, n:m]: 텐서 z의 n번 행부터 마지막 행 까지 값 중에 n번 열부터 m-1열의 값
- z[:, 1:]  : 텐서 z의 1번 열부터 마지막 열까지 값

# k_tensor_reshaping.py

In [22]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


구조 변경
- view(n,m): 텐서의 구조를 (n,m)으로 변경
- reshape(n,m): 텐서의 구조를 (n,m)으로 변경
- squeeze(): 크기가 1인 모든 차원을 제거한다.
- squeeze(n): n번재 차원의 크기가 1이면 해당 차원을 제거한다.
- unsqueeze(n): n번째 차원으로 크기가 1인 차원을 추가한다.
- tensor.flatten(): 다차원 텐서를 1차원으로 변경한다.(평탄화)
- torch.flatten(tensor): 텐서를 1차원으로 변경한다.
- torch.flatten(tensor,start_dim=n): 텐서를 n번째 차원부터 평탄화를 진행한다.
- permute(tensor, (n,m,k)): 텐서의 차원을 n,m,k로 재배열한다. 예를 들어 (2,3,5)형태의 텐서를 permute(tensor,(2,0,1)하면 (5,2,3)형태로 텐서의 구조가 변경된다.
- transpose(tensor, n, m): n번 차원과 m번 차원을 교환
- t(tensor): 2차원 텐서의 전치(행과 열을 교환)

# l_tensor_concat.py

In [23]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

텐서의 병합
- cat([tensor1,tensor2,...], dim=n): n번째 차원을 기준으로 tensor를 병합
- cat((tensor1,tensor2,...), dim=n): n번째 차원을 기준으로 tensor를 병합

# m_tensor_stacking.py

In [24]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


stack vs cat
stack((tensor1, tensor2), dim=n) vs cat((tensor1, tensor2), dim=n)
- 모두 동일한 결과가 나온다.

# n_tensor_vstack_hstack.py

In [25]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


vstack, hstack
- vstack((tensor1, tensor2)): 두 개의 텐서를 첫 번째 차원에서 쌓는다.
- hstack((tensor1, tensor2)): 두 개의 텐서를 두 번째 차원에서 쌓는다.

# 숙제 후기
텐서의 병합 파트가 생각한 것 보다 어렵다. 몇 번더 보고, 해볼 필요가 있다고 생각했다.
